name: 🚀 Feature request
description: Suggest a feature that will improve the project
labels: [pending triage]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what you think would be a helpful addition the project.
      placeholder: Feature description
    validations:
      required: true
